### ISSUE TITLE
Error on comparison

### ISSUE THREAD

**Issue by dorli** [kikito/semver.lua#2]
The following code cause an error:

```
local v = require 'semver'
if semver'1.2.3' < semver'1.2.3-alpha' then
  print('xxx')
end
```

Error:

```
semver.lua:39: attempt to index local 'str' (a nil value)
```

**Comment by kikito** [comment]
Hi there,

It seems you have found a bug in semver.lua - I did not test the edge cases well enough. I am adding more tests and fixing them. It might still take me 1 or 2 days. Sorry!

**Comment by kikito** [comment]
Hi,

I have fixed this error, as well as another big one, and released a new version of the luarock. You should be able to get it from luarocks (or by downloading the most recent file)

The other great change I made is: in semver, build information should be ignored for the purposes of comparison. (so `semver'1.2.3' == semver'1.2.3+build', even if they have different builds). The prereleases (starting with`-`instead of`+`) are used, and I've made the comparator more robust (I had overlooked some edge cases when implementing it), so your example should work now after you update the library. Please reopen this if that's not the case.
